/* The following code was generated by JFlex 1.4.1 on 4/16/13 3:04 PM */

/*
 * Generated on 4/16/13 3:07 PM
 */
package editor;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class AssemblyTextAreaTokenMaker extends AbstractJFlexTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 1;
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\21\1\10\1\0\1\21\1\17\22\0\1\21\1\37\1\15"+
    "\1\20\1\1\1\37\1\37\1\7\2\40\1\37\1\30\1\37\1\30"+
    "\1\31\1\41\1\4\1\71\1\73\1\16\1\74\1\72\2\6\1\3"+
    "\1\3\1\45\1\22\1\17\1\37\1\17\1\37\1\20\1\54\1\47"+
    "\1\61\1\55\1\27\1\25\1\56\1\1\1\52\1\65\1\1\1\24"+
    "\1\62\1\53\1\67\1\63\1\1\1\60\1\66\1\51\1\70\1\64"+
    "\1\1\1\23\1\50\1\57\1\40\1\11\1\40\1\17\1\2\1\0"+
    "\1\5\1\14\1\5\1\25\1\33\1\26\1\1\1\42\1\44\2\1"+
    "\1\34\1\1\1\13\1\1\1\43\1\1\1\13\1\35\1\32\1\12"+
    "\1\1\1\46\1\23\2\1\1\36\1\17\1\36\1\37\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\2\1\6"+
    "\1\7\2\2\1\10\12\2\1\11\1\12\3\11\1\1"+
    "\1\13\1\3\1\14\1\13\1\14\1\13\1\15\1\13"+
    "\1\4\1\16\1\0\1\4\1\2\2\0\6\2\4\17"+
    "\4\2\1\20\4\0\1\1\1\14\1\0\2\15\1\4"+
    "\1\21\2\4\1\16\1\4\5\0\1\1\1\4\1\20"+
    "\2\0\1\22\1\1\1\4\2\0\1\1\1\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\u01ab\0\u01e8\0\u01ab\0\u0225\0\u0262\0\u01ab\0\u029f\0\u02dc"+
    "\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4"+
    "\0\u0501\0\u01ab\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u0632"+
    "\0\u0632\0\u066f\0\u06ac\0\u06e9\0\u0726\0\u0763\0\u07a0\0\u01ab"+
    "\0\u07dd\0\u081a\0\u0857\0\u0894\0\u08d1\0\u090e\0\u094b\0\u0988"+
    "\0\u09c5\0\u0a02\0\u0a3f\0\267\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33"+
    "\0\u0b70\0\u0bad\0\u0bea\0\267\0\u0c27\0\u0c64\0\u0ca1\0\u0cde"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0632\0\u0dd2\0\u0e0f\0\u01ab\0\u0e4c"+
    "\0\u0e89\0\u07dd\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7"+
    "\0\u1034\0\u1071\0\u01ab\0\u10ae\0\u10eb\0\u1128\0\u1165\0\u11a2"+
    "\0\u11df\0\u1128\0\u121c\0\u1259";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\4\1\5\1\7\1\10"+
    "\1\3\3\4\1\11\1\5\1\11\1\3\1\12\1\13"+
    "\1\4\1\14\3\4\1\11\1\15\4\4\1\16\1\11"+
    "\1\16\1\11\3\4\1\11\1\4\1\17\1\4\1\20"+
    "\2\4\1\21\1\22\2\4\1\23\1\24\1\25\2\4"+
    "\1\26\1\27\1\30\1\4\4\5\10\31\1\32\15\31"+
    "\1\33\13\31\1\34\3\31\1\35\26\31\7\3\2\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\5\3\2\0"+
    "\4\3\4\0\3\3\1\0\30\3\6\4\2\0\1\36"+
    "\3\4\1\0\1\4\1\0\1\3\2\0\5\4\2\0"+
    "\4\4\4\0\3\4\1\0\27\4\3\37\2\5\1\37"+
    "\1\5\2\0\4\37\1\0\1\5\1\0\1\37\2\0"+
    "\1\37\1\40\2\41\1\42\1\0\1\43\1\37\1\42"+
    "\1\40\1\37\4\0\3\37\1\0\7\37\1\41\13\37"+
    "\4\5\3\37\1\44\1\45\1\37\1\45\2\0\4\37"+
    "\1\0\1\45\1\0\1\37\2\0\1\46\1\40\2\41"+
    "\1\42\1\0\1\43\1\37\1\42\1\40\1\37\4\0"+
    "\3\37\1\0\7\37\1\41\13\37\4\45\7\47\1\50"+
    "\1\51\1\52\63\47\116\0\1\12\53\0\1\3\6\4"+
    "\2\0\1\36\3\4\1\0\1\4\1\0\1\3\2\0"+
    "\5\4\2\0\4\4\4\0\3\4\1\0\7\4\1\53"+
    "\17\4\3\0\2\43\1\0\1\43\7\0\1\43\30\0"+
    "\1\54\2\0\1\55\16\0\4\43\1\3\6\4\2\0"+
    "\1\36\3\4\1\0\1\4\1\0\1\3\2\0\1\4"+
    "\1\56\3\4\2\0\4\4\4\0\3\4\1\0\5\4"+
    "\1\57\2\4\1\56\1\4\1\57\14\4\1\3\6\4"+
    "\2\0\1\36\3\4\1\0\1\4\1\0\1\3\2\0"+
    "\5\4\2\0\4\4\4\0\3\4\1\0\12\4\1\60"+
    "\14\4\1\3\6\4\2\0\1\36\3\4\1\0\1\4"+
    "\1\0\1\3\2\0\5\4\2\0\4\4\4\0\3\4"+
    "\1\0\5\4\1\61\1\4\1\62\17\4\1\3\6\4"+
    "\2\0\1\36\3\4\1\0\1\4\1\0\1\3\2\0"+
    "\5\4\2\0\4\4\4\0\3\4\1\0\4\4\1\63"+
    "\22\4\1\3\3\4\1\64\2\4\2\0\1\36\3\4"+
    "\1\0\1\65\1\0\1\3\2\0\5\4\2\0\4\4"+
    "\4\0\3\4\1\0\23\4\1\66\1\64\1\67\1\64"+
    "\1\3\6\4\2\0\1\36\3\4\1\0\1\4\1\0"+
    "\1\3\2\0\5\4\2\0\4\4\4\0\3\4\1\0"+
    "\14\4\1\60\12\4\1\3\6\4\2\0\1\36\3\4"+
    "\1\0\1\4\1\0\1\3\2\0\5\4\2\0\4\4"+
    "\4\0\3\4\1\0\21\4\1\63\1\70\4\4\1\3"+
    "\6\4\2\0\1\36\3\4\1\0\1\4\1\0\1\3"+
    "\2\0\5\4\2\0\4\4\4\0\3\4\1\0\14\4"+
    "\1\71\3\4\1\30\6\4\1\3\6\4\2\0\1\36"+
    "\3\4\1\0\1\4\1\0\1\3\2\0\5\4\2\0"+
    "\4\4\4\0\3\4\1\0\3\4\1\72\16\4\1\73"+
    "\4\4\1\3\6\4\2\0\1\36\3\4\1\0\1\4"+
    "\1\0\1\3\2\0\5\4\2\0\4\4\4\0\3\4"+
    "\1\0\12\4\1\74\14\4\10\31\1\0\15\31\1\0"+
    "\13\31\1\0\3\31\1\0\26\31\32\0\1\75\11\0"+
    "\1\76\62\0\1\77\110\0\1\100\26\0\7\3\2\0"+
    "\1\3\1\101\2\3\1\0\1\3\1\0\1\3\2\0"+
    "\5\3\2\0\4\3\4\0\3\3\1\0\27\3\7\37"+
    "\2\0\4\37\1\0\1\37\1\0\1\37\2\0\5\37"+
    "\2\0\4\37\4\0\3\37\1\0\32\37\2\102\1\37"+
    "\1\102\2\0\4\37\1\0\1\102\1\0\1\37\2\0"+
    "\5\37\1\103\1\0\4\37\4\0\3\37\1\0\23\37"+
    "\4\102\3\37\2\43\1\37\1\43\2\0\4\37\1\0"+
    "\1\43\1\0\1\37\2\0\2\37\2\41\1\42\2\0"+
    "\1\37\1\42\2\37\4\0\3\37\1\0\7\37\1\41"+
    "\13\37\4\43\3\37\2\44\1\37\1\44\2\0\4\37"+
    "\1\0\1\44\1\0\1\37\2\0\2\37\2\41\1\42"+
    "\1\0\1\43\1\37\1\42\2\37\4\0\3\37\1\0"+
    "\7\37\1\41\13\37\4\44\3\37\1\44\1\45\1\37"+
    "\1\45\2\0\4\37\1\0\1\45\1\0\1\37\2\0"+
    "\1\37\1\104\2\41\1\42\1\0\1\43\1\37\1\42"+
    "\1\104\1\37\4\0\3\37\1\0\7\37\1\41\13\37"+
    "\4\45\3\37\4\105\2\0\3\37\1\105\1\0\1\105"+
    "\1\0\1\37\2\0\2\37\3\105\2\0\1\37\1\105"+
    "\2\37\4\0\3\37\1\0\1\37\1\105\4\37\2\105"+
    "\3\37\1\105\7\37\4\105\7\106\1\107\1\0\64\106"+
    "\7\0\1\107\65\0\4\106\1\110\1\106\1\111\1\112"+
    "\1\0\1\47\1\113\3\47\1\110\7\106\1\47\3\106"+
    "\1\47\36\106\1\110\1\111\1\110\1\111\1\3\6\4"+
    "\2\0\1\36\3\4\1\0\1\4\1\0\1\3\2\0"+
    "\5\4\2\0\4\4\4\0\3\4\1\0\1\4\1\74"+
    "\4\4\1\74\3\4\1\74\14\4\50\0\1\114\77\0"+
    "\1\114\21\0\1\3\6\4\2\0\1\36\3\4\1\0"+
    "\1\4\1\0\1\3\2\0\5\4\2\0\4\4\4\0"+
    "\3\4\1\0\3\4\1\74\23\4\1\3\6\4\2\0"+
    "\1\36\3\4\1\0\1\4\1\0\1\3\2\0\5\4"+
    "\2\0\4\4\4\0\3\4\1\0\11\4\1\74\15\4"+
    "\1\3\6\4\2\0\1\36\3\4\1\0\1\4\1\0"+
    "\1\3\2\0\5\4\2\0\4\4\4\0\3\4\1\0"+
    "\15\4\1\74\11\4\1\3\6\4\2\0\1\36\3\4"+
    "\1\0\1\4\1\0\1\3\2\0\5\4\2\0\4\4"+
    "\4\0\3\4\1\0\7\4\1\74\17\4\1\3\6\4"+
    "\2\0\1\36\3\4\1\0\1\4\1\0\1\3\2\0"+
    "\5\4\2\0\4\4\4\0\3\4\1\0\4\4\1\74"+
    "\2\4\1\74\17\4\1\3\6\4\2\0\1\36\3\4"+
    "\1\0\1\4\1\0\1\3\2\0\5\4\2\0\4\4"+
    "\4\0\3\4\1\0\16\4\1\74\10\4\1\3\3\4"+
    "\1\64\2\4\2\0\1\36\3\4\1\0\1\4\1\0"+
    "\1\3\2\0\5\4\2\0\4\4\4\0\3\4\1\0"+
    "\23\4\1\64\3\4\1\3\6\4\2\0\1\36\3\4"+
    "\1\0\1\4\1\0\1\3\2\0\5\4\2\0\4\4"+
    "\4\0\3\4\1\0\24\4\1\64\2\4\1\3\2\4"+
    "\1\64\3\4\2\0\1\36\3\4\1\0\1\4\1\0"+
    "\1\3\2\0\5\4\2\0\4\4\4\0\3\4\1\0"+
    "\27\4\1\3\6\4\2\0\1\36\3\4\1\0\1\4"+
    "\1\0\1\3\2\0\1\4\1\74\3\4\2\0\4\4"+
    "\4\0\3\4\1\0\27\4\1\3\6\4\2\0\1\36"+
    "\3\4\1\0\1\4\1\0\1\3\2\0\5\4\2\0"+
    "\4\4\4\0\3\4\1\0\12\4\1\74\2\4\1\74"+
    "\11\4\1\3\6\4\2\0\1\36\3\4\1\0\1\4"+
    "\1\0\1\3\2\0\5\4\2\0\4\4\4\0\3\4"+
    "\1\0\1\4\1\74\10\4\1\74\14\4\1\3\6\4"+
    "\2\0\1\36\3\4\1\0\1\4\1\0\1\3\2\0"+
    "\5\4\2\0\4\4\4\0\3\4\1\0\1\4\1\74"+
    "\25\4\43\0\1\115\65\0\1\116\72\0\1\117\110\0"+
    "\1\120\26\0\3\3\4\121\2\0\3\3\1\121\1\0"+
    "\1\121\1\0\1\3\2\0\2\3\3\121\2\0\1\3"+
    "\1\121\2\3\4\0\3\3\1\0\1\3\1\121\4\3"+
    "\2\121\3\3\1\121\7\3\4\121\3\37\2\102\1\37"+
    "\1\102\2\0\4\37\1\0\1\102\1\0\1\37\2\0"+
    "\2\37\2\41\1\37\2\0\4\37\4\0\3\37\1\0"+
    "\7\37\1\41\13\37\4\102\3\0\2\102\1\0\1\102"+
    "\7\0\1\102\52\0\4\102\3\37\4\105\2\0\3\37"+
    "\1\105\1\0\1\105\1\0\1\37\2\0\1\37\1\104"+
    "\3\105\2\0\1\37\1\105\1\104\1\37\4\0\3\37"+
    "\1\0\1\37\1\105\4\37\2\105\3\37\1\105\7\37"+
    "\4\105\7\106\1\50\1\0\70\106\1\111\1\106\1\111"+
    "\1\107\1\0\5\106\1\111\52\106\4\111\4\106\1\47"+
    "\1\106\1\47\1\107\1\0\5\106\1\47\52\106\4\47"+
    "\3\106\4\122\1\50\1\0\3\106\1\122\1\106\1\122"+
    "\6\106\3\122\3\106\1\122\13\106\1\122\4\106\2\122"+
    "\3\106\1\122\7\106\4\122\51\0\1\123\70\0\1\124"+
    "\62\0\1\115\104\0\1\125\62\0\1\126\43\0\3\3"+
    "\4\127\2\0\3\3\1\127\1\0\1\127\1\0\1\3"+
    "\2\0\2\3\3\127\2\0\1\3\1\127\2\3\4\0"+
    "\3\3\1\0\1\3\1\127\4\3\2\127\3\3\1\127"+
    "\7\3\4\127\3\106\4\130\1\50\1\0\3\106\1\130"+
    "\1\106\1\130\6\106\3\130\3\106\1\130\13\106\1\130"+
    "\4\106\2\130\3\106\1\130\7\106\4\130\41\0\1\131"+
    "\70\0\1\115\7\0\1\124\30\0\1\126\1\132\4\126"+
    "\1\132\2\0\3\126\1\0\1\126\1\0\1\132\1\0"+
    "\1\132\5\126\2\132\4\126\1\0\2\132\4\126\1\132"+
    "\27\126\3\3\4\133\2\0\3\3\1\133\1\0\1\133"+
    "\1\0\1\3\2\0\2\3\3\133\2\0\1\3\1\133"+
    "\2\3\4\0\3\3\1\0\1\3\1\133\4\3\2\133"+
    "\3\3\1\133\7\3\4\133\3\106\4\134\1\50\1\0"+
    "\3\106\1\134\1\106\1\134\6\106\3\134\3\106\1\134"+
    "\13\106\1\134\4\106\2\134\3\106\1\134\7\106\4\134"+
    "\41\0\1\126\33\0\3\3\4\4\2\0\3\3\1\4"+
    "\1\0\1\4\1\0\1\3\2\0\2\3\3\4\2\0"+
    "\1\3\1\4\2\3\4\0\3\3\1\0\1\3\1\4"+
    "\4\3\2\4\3\3\1\4\7\3\4\4\3\106\4\47"+
    "\1\50\1\0\3\106\1\47\1\106\1\47\6\106\3\47"+
    "\3\106\1\47\13\106\1\47\4\106\2\47\3\106\1\47"+
    "\7\106\4\47";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4758];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\5\1\2\11\1\1\1\11\2\1\1\11\13\1"+
    "\1\11\15\1\1\11\1\0\2\1\2\0\17\1\4\0"+
    "\2\1\1\0\3\1\1\11\4\1\5\0\2\1\1\11"+
    "\2\0\3\1\2\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public AssemblyTextAreaTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return null;
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			/* No multi-line comments */
			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new DefaultToken();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AssemblyTextAreaTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AssemblyTextAreaTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 19: break;
        case 17: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 20: break;
        case 6: 
          { addToken(Token.WHITESPACE);
          }
        case 21: break;
        case 13: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 22: break;
        case 12: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 23: break;
        case 16: 
          { addToken(Token.RESERVED_WORD);
          }
        case 24: break;
        case 8: 
          { addToken(Token.SEPARATOR);
          }
        case 25: break;
        case 2: 
          { addToken(Token.IDENTIFIER);
          }
        case 26: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 27: break;
        case 4: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 28: break;
        case 1: 
          { addToken(Token.ERROR_IDENTIFIER);
          }
        case 29: break;
        case 15: 
          { addToken(Token.DATA_TYPE);
          }
        case 30: break;
        case 14: 
          { addToken(Token.ERROR_CHAR);
          }
        case 31: break;
        case 18: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 32: break;
        case 11: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 33: break;
        case 7: 
          { start = zzMarkedPos-1; yybegin(EOL_COMMENT);
          }
        case 34: break;
        case 3: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 35: break;
        case 9: 
          { 
          }
        case 36: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 93: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 94: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
